platform :ios, '8.0'
use_frameworks!

pod 'AFNetworking', '~> 2.0'
pod 'MJExtension'
pod 'Masonry', '~> 0.6.3'
pod 'YTKNetwork'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'MBProgressHUD'
pod 'SVProgressHUD'